habbit/urls.py
from django.urls import path
from . import views

app_name = "tasks"

urlpatterns = [
   path("", views.index, name="index"),
   path("add", views.add_task, name="add_task"),
   path("edit/<int:id>/", views.editing, name="editing"),
   path("deleting/<int:id>/", views.deleting, name="deleting")
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('habbit/', include("habbit.urls"))
]

habbit/models.py
from django.db import models


# Create your models here.
class Tasks(models.Model):
    name = models.CharField(max_length=64)
    description = models.CharField(max_length=128)
    objects = models.Manager()

    def __str__(self):
        return f"{self.name}"

habbit/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from .models import Tasks
# Create your views here.


class NewTaskForm(forms.Form):
    name = forms.CharField(label="Name your task")
    description = forms.CharField(label="Tell more about task")


def index(request):
    # if "list_of_tasks" not in request.session:
    #     request.session["list_of_tasks"] = []
    print(Tasks.objects.all())
    return render(request, 'habbit/index.html',
                  {
                      "list_of_tasks": Tasks.objects.all()
                      # "list_of_tasks": request.session["list_of_tasks"]
                  })


def add_task(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            new_task = Tasks(name = form.cleaned_data["name"], description = form.cleaned_data["description"])
            new_task.save()
            # request.session["list_of_tasks"] += [name]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, 'habbit/add.html', {
                "form": form
            })
    return render(request, 'habbit/add.html', {
        "form": NewTaskForm()
    })


def editing(request, id):
    task = get_object_or_404(Tasks, id=id)

    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task.name = form.cleaned_data["name"]
            task.description = form.cleaned_data["description"]
            task.save()
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, 'habbit/edit.html', {
                "form": form,
                "task": task
            })
    return render(request, 'habbit/edit.html', {
        "form": NewTaskForm(initial={'name': task.name, 'description': task.description}),
        "task": task
    })


def deleting(request, id):
    task = get_object_or_404(Tasks, id=id)
    Tasks.delete(task)
    return HttpResponseRedirect(reverse("tasks:index"))

habbit/templates/habbit/add.html
{% extends "habbit/layout.html"%}
{% block body %}
    <h1>Add task</h1>
        <form action="{% url 'tasks:add_task' %}" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit">
        </form>
    <a href="{% url 'tasks:index' %}">Go back to list of tasks)</a>
{% endblock %}

habbit/templates/habbit/edit.html
{% extends "habbit/layout.html"%}
{% block body%}
    <h1>Edit task</h1>
        <form action="{% url 'tasks:editing' task.id %}" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit">
        </form>
    <a href="{% url 'tasks:index' %}">Go back to list of tasks))</a>
{% endblock %}

habbit/templates/habbit/index.html
{% extends "habbit/layout.html"%}

{% block body %}
    <h1> Hi there, how are you? There is your`s TODO LIST</h1>
        <div>
            <ul>
                {% for task in list_of_tasks %}
                    <li> {{task.name}} </li>
                    <ul>
                        <li> {{ task.description}} </li>
                    </ul>
                    <div id="buttons">
                        <a href="{% url 'tasks:editing' task.id  %}" >Edit</a>
                        <a href = "{% url 'tasks:deleting' task.id %}">DELETE?!</a>
                    </div>
                {% empty %}
                    <li>You have no tasks for now :)</li>
                {% endfor %}
            </ul>
            <a href="{% url 'tasks:add_task' %}"> Add a New Task !</a>
        </div>
{% endblock %}

habbit/templates/habbit/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="UTF-8">
      <title>Tasks</title>
  </head>
  <body>
    {% block body %}
    {% endblock %}
  </body>
</html>